# Generated by Django 3.2.25 on 2024-05-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicio.servicio')),
                ('presupuesto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
            ],
            bases=('servicio.servicio', models.Model),
        ),
        migrations.CreateModel(
            name='ServicioOfrecido',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicio.servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible_desde', models.DateField()),
                ('disponible_hasta', models.DateField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
            bases=('servicio.servicio', models.Model),
        ),
    ]
