# Generated by Django 3.2.25 on 2024-05-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicioContratado',
            new_name='ContratarServicio',
        ),
        migrations.RenameModel(
            old_name='ServicioOfrecido',
            new_name='OfrecerServicio',
        ),
    ]
