# Generated by Django 3.2.25 on 2024-05-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuario',
        ),
    ]
